create up to 50 revisions of the same tag

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -110,10 +110,21 @@ jobs:
       - name: Chmod AppImages
         run: chmod +x artifact/*/*.AppImage
       - run: |
-          gh release create \
-            "rev-$REVISION" \
-            --notes "automatic release of https://github.com/mrshmllow/affinity-nix/commit/$REVISION" \
-            artifact/*/*.AppImage
+          for i in {1..50}; do
+            if gh release create \
+              "rev-$REVISION-$i" \
+              --notes "automatic release of https://github.com/mrshmllow/affinity-nix/commit/$REVISION" \
+              artifact/*/*.AppImage 2>&1 | \
+              tee /dev/tty | \
+              grep -q "a release with the same tag name already exists"; then
+                echo "revision $i exists, skipping to next."
+            else
+                echo "failed to create gh release."
+                exit 1
+            fi
+          done
+          
+          echo "failed to create gh release."
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           REVISION: ${{ needs.check.outputs.revision }}
